---
  - name: Playbook
    hosts: nginx
    vars:
      repo: github.com/Big-Vi/laravel-ansible-terraform.git
      branch: main
      git_username: big-vi
      web_server_root: /var/www/example.com/
      git_private_ssh_key: ~/.ssh/id_rsa
      domain_name: example.com
      certbot_email: dummyemail@gmail.com
    become: true
    become_user: root

    tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add ppa Repository
      apt_repository: repo=ppa:ondrej/php

    - name: Install required packages
      apt:
        name: ['php8.2', 'php8.2-cli', 'php8.2-fpm', 'php8.2-common', 'php8.2-curl', 'php8.2-mbstring', 
          'php8.2-xml', 'php8.2-pgsql', 'composer', 'git', 'nginx', 'python3-pip', 'certbot', 'python3-certbot-nginx']
        state: present

    - name: Install Boto3
      pip:
        name: boto3
        state: present

    - name: Start and enable PHP-FPM service
      systemd:
        name: php8.2-fpm
        state: started
        enabled: yes

    - name: Delete contents of the directory
      file:
        path: "{{ web_server_root }}"
        state: absent

    - name: Create directory if it doesn't exist
      file:
        path: "{{ web_server_root }}"
        state: directory
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0757'

    - name: Clone the private Git repository
      command: git clone -b {{ branch }} https://{{ git_username }}:{{ lookup('aws_ssm', 'Git_Personal_Access_Token' ) }}@{{ repo }} .
      args:
        chdir: "{{ web_server_root }}"
      become_user: ubuntu

    - name: set permissions for Laravel storage folder
      file:
          path: "{{ web_server_root }}/storage"
          state: directory
          recurse: yes
          mode: '0755'
      
    - name: Install Composer dependencies
      command: composer install --optimize-autoloader --no-dev
      args:
        chdir: "{{ web_server_root }}"
      become_user: ubuntu
      changed_when: false

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-available/{{ domain_name }}"
      notify:
        - Reload Nginx

    - name: Enable Nginx site
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        state: link

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Run Python script to create .env
      command: python3 infra/main/create_env_file.py
      args:
        chdir: "{{ web_server_root }}"

    - name: Migrate
      command: php artisan migrate --force
      args:
        chdir: "{{ web_server_root }}"

    - name: Run Certbot to obtain SSL certificate
      command: >
        certbot --nginx -d {{ domain_name }} -d www.{{ domain_name }} -m {{ certbot_email }}
        --non-interactive --agree-tos

    handlers:
      - name: Reload Nginx
        service:
          name: nginx
          state: reloaded
