---
  - name: Playbook
    hosts: nginx
    become: true
    become_user: root

    tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add ppa Repository
      apt_repository: repo=ppa:ondrej/php

    - name: Install required packages
      apt:
        name: ['php8.2', 'php8.2-cli', 'php8.2-fpm', 'php8.2-common', 'php8.2-curl', 'php8.2-mbstring', 
          'php8.2-xml', 'php8.2-sqlite3', 'composer', 'git', 'nginx', 'python3-pip', 'certbot', 'python3-certbot-nginx']
        state: present

    - name: Install Boto3
      pip:
        name: boto3
        state: present

    - name: Start and enable PHP-FPM service
      systemd:
        name: php8.2-fpm
        state: started
        enabled: yes

    - name: Remove existing content of the directory
      file:
        path: /var/www/test.ulearn.nz
        state: absent
      changed_when: false

    - name: Provide ownership of app folder
      file:
          path: /var/www/test.ulearn.nz
          owner: "ubuntu"
          group: "ubuntu"
          mode: '0755'
          recurse: yes

    - name: Copy Git private key to remote server
      copy:
        src: ~/.ssh/id_rsa-personal
        dest: ~/.ssh/id_rsa
        mode: '0600'
      become_user: ubuntu

    - name: Add GitHub SSH Key to known_hosts
      known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        path: /home/ubuntu/.ssh/known_hosts
      become_user: ubuntu
      
    - name: Clone the private Git repository
      command: git clone -b laravel-ansible-tf git@github.com:Big-Vi/laravel-ansible-terraform.git .
      args:
        chdir: /var/www/test.ulearn.nz
      become_user: ubuntu

    - name: set permissions for Laravel storage folder
      file:
          path: /var/www/test.ulearn.nz/storage
          state: directory
          recurse: yes
          mode: '0757'
      
    - name: Install Composer dependencies
      command: composer install --optimize-autoloader --no-dev
      args:
        chdir: /var/www/test.ulearn.nz
      become_user: ubuntu
      changed_when: false

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/test.ulearn.nz
      notify:
        - Reload Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/test.ulearn.nz
        dest: /etc/nginx/sites-enabled/test.ulearn.nz
        state: link

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Run Python script to create .env
      command: python3 infra/create_env_file.py
      args:
        chdir: /var/www/test.ulearn.nz

    - name: Clear the table content
      command: php artisan migrate
      args:
        chdir: /var/www/test.ulearn.nz

    - name: Run Certbot to obtain SSL certificate
      command: >
        certbot --nginx -d test.ulearn.nz -d www.test.ulearn.nz -m itservices@core-ed.org
        --non-interactive --agree-tos

    handlers:
      - name: Reload Nginx
        service:
          name: nginx
          state: reloaded
